version: "3.7"

volumes:
  pb_data:
  pb_public:
  pb_hooks:  

services:
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    command:
      - --encryptionEnv #optional
      - ENCRYPTION #optional
    environment:
      ENCRYPTION: example #optional
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/pb_data
      - ./frontend/dist/frontend:/pb_public 
      - pb_hooks:/pb_hooks       
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5    

  frontend:
    build: "./frontend/."
    environment:
      - PBSERVER=pocketbase
    ports: 80:80
